// THIS IS PUBLIC DOMAIN CODE MOSTLY GENERATED BY AI 
#include <stdio.h>
#include <stdlib.h>
#include <dos.h> 

#define VIDEO_MEMORY 0xB800 
#define SCREEN_WIDTH 79 
#define SCREEN_HEIGHT 24 

void putch_attr(int x, int y, unsigned char character, unsigned char attribute) {

    unsigned int offset = (y * SCREEN_WIDTH + x) * 2;

    char far* video_mem = MK_FP(VIDEO_MEMORY, 0);

    *(video_mem + offset) = character;
    *(video_mem + offset + 1) = attribute;
}

void main() {
    int i;
    int block_x[4], block_y[4];
    int block_dx[4], block_dy[4];
    unsigned char block_char[4];
    unsigned char block_attr[4];     

    for (i = 0; i < 4; i++) {
        block_x[i] = rand() % (SCREEN_WIDTH - 1);
        block_y[i] = rand() % (SCREEN_HEIGHT - 1);
        block_dx[i] = (rand() % 2 == 0) ? 1 : -1; 
        block_dy[i] = (rand() % 2 == 0) ? 1 : -1; 
        block_char[i] = 6;
        block_attr[i] = 26;
    }

    while (!kbhit()) { 
         sound(100 + rand() % 1901);  
         delay(10);
         nosound();
        
        for (i = 0; i < 4; i++) {
            putch_attr(block_x[i], block_y[i], ' ', 0x00); 
        }

        for (i = 0; i < 4; i++) {
            block_x[i] += block_dx[i];
            block_y[i] += block_dy[i];

            if (block_x[i] < 0 || block_x[i] >= SCREEN_WIDTH) {
                block_dx[i] *= -1;
            }
            if (block_y[i] < 0 || block_y[i] >= SCREEN_HEIGHT) {
                block_dy[i] *= -1;
            }
        }

        for (i = 0; i < 4; i++) {
            putch_attr(block_x[i], block_y[i], block_char[i], block_attr[i]);
        }
        
        delay(60); 
    }
 _exit( EXIT_SUCCESS );
}
